In [1]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('play_tennis.csv',usecols=['outlook', 'temp', 'humidity','wind', 'play'])

In [4]:
df

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [5]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [6]:
py=9/14
pn=5/14

In [7]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [8]:
#outlook
pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [9]:
pon=0
prn=2/5
psn=2/5

poy=4/9
pry=3/9
psy=2/9

In [10]:
#temp
pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [11]:
pcoolno=1/5
photno=2/5
pmildno=2/5

pcoolyes=3/9
photyes=2/9
pmildyes=4/9

In [12]:
#humidity
pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [13]:
phighno=4/5
pnormal=1/5

phighyes=3/9
pnormalyes=6/9

In [14]:
#wind
pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [17]:
pstrongno=3/5
pweakno=2/5

pstrongyes=3/9
pweakyes=6/9

In [20]:
# outlook = Sunny, Temp = Hot , Humidity = HIgh, wind = weak
# Play or No play?
Pyes=py*psy*photyes*phighyes*pweakyes
Pyes

0.007054673721340388

In [21]:
Pno=pn*psn*photno*phighno*pweakno
Pno

0.01828571428571429

In [ ]:
Pno>Pyes
So no play